### ISSUE TITLE
Doesn't find a named export

### ISSUE THREAD

**Issue by citycide** [standard-things/esm#15]
Thanks for your efforts on this! Hope it gets around.

See repro at https://github.com/citycide/std-esm-repro.

```js
// index.js

require('@std/esm')

const file = require('./file.js')
module.exports = file

console.log(file)
```

```js
// file.js

import { SOME_CONSTANT_THING as thing } from './constants'

export default function fn () {
  return thing
}
```

```js
// constants.js

export const SOME_CONSTANT_THING = 'forty-six barrels of bleh'
```

Running `node index.js` seems to run the first time, though `const file = require('./file.js')` doesn't give me what I expect, just an object containing the `esm` added Symbol, which gets logged:

```js
{ [Symbol(@std/esm:sourceType)]: 'module' }
```

On second run ( like from cache ), this is thrown:

```
SyntaxError: Module 'constants.js' does not provide an export named 'SOME_CONSTANT_THING'
    at Object.<anonymous> (/home/........../repro/file.js)
    at Object.<anonymous> (/home/........../repro/file.js)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

`@std/esm` v0.1.1
node v8.3.0
npm v5.3.0
Ubuntu 14.04.5

**Comment by jdalton** [comment]
Hi @citycide!

I've fixed part of the problem, `"all"` support, with 0.2.0 but there's still a cjs bridge issue left. I should have it tackled by this evening.

**Comment by isnifer** [comment]
Same here:
```js
// core/cli.js
import { log } from 'winston'
```

```js
// winston code

var winston = exports;
//
// Pass through the target methods onto `winston`.
//
var methods = [
  'log',
  'query',
  'stream',
  'add',
  'remove',
  'clear',
  'profile',
  'startTimer',
  'extend',
  'cli',
  'handleExceptions',
  'unhandleExceptions',
  'configure'
];
common.setLevels(winston, null, defaultLogger.levels);
methods.forEach(function (method) {
  winston[method] = function () {
    return defaultLogger[method].apply(defaultLogger, arguments);
  };
});
```
```sh
> node -r @std/esm core/cli.js

SyntaxError: Module 'winston.js' does not provide an export named 'log'
```
```json
"@std/esm": {
  "esm": "js"
 }
```

**Comment by charlike** [comment]
Still not work for me, 0.2.1 too. In my case i just have `export default () => {}` and when trying to require it it says that this file don't have export named `default`?

Node 8.2, npm 5.3, ArchLinux. The case

index.js
```js
export const bar = 'barry'
export default () => Promise.resolve(123)
```

foo.js

```js
require('@std/esm')

const bar = require('./bar')

console.log(bar)
```

empty object when `node foo.js`, error `import Unexpected token` when `node -r @std/esm foo.js`

Actually always getting empty object, even with just named export

index.js

```js
export const bar = {
  bar: () => Promise.resolve(123),
}
```

**Comment by charlike** [comment]
@jdalton, we all probably not getting something correct. How to use this? Plus better docs :)

**Comment by charlike** [comment]
Okey i think i get what is happening. It seems that both `esm: js` and `cjs: true` doesn't work well together.

When we don't set `cjs: true`, default exports work.

**Comment by jdalton** [comment]
Yeah, I'm still working on the second bit, the `"cjs":true` bridge.

**Comment by aemino** [comment]
For me, this issue occurs even with the default settings.

**Comment by charlike** [comment]
Yup, just named exports not work for esm mode.

**Comment by busticated** [comment]
i'm having problems as well:

one.js

    require('@std/esm');
    const log = require('./two.mjs').default;
    log();

two.mjs

    export default function(){ console.log('ok!'); };

when i fire it up via: `$ node one.js`, i get:

    /path/to/my/project/one.js:4
    log();
    ^

    TypeError: log is not a function
        at Object.<anonymous> (/path/to/my/project/one.js:4:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.runMain (module.js:604:10)
        at run (bootstrap_node.js:389:7)
        at startup (bootstrap_node.js:149:9)
        at bootstrap_node.js:504:3

I get the same error when I rename `two.mjs -> two.js` and opt into unambiguous `.js` use via `"@std/esm": { "esm": "js" }` in my package.json file.

@std/esm v0.2.1, node v6.11.1, macOS 10.12.6

**Comment by jdalton** [comment]
I'm snipping back the conversation because I'm aware of the issue and continued reports after the fact are just distracting.

**Comment by jdalton** [comment]
Closed by https://github.com/standard-things/esm/commit/63558925710e119f2ee2a0407d1299d2d34d44dc.
